### ISSUE TITLE
Update the title of the release note page

### ISSUE THREAD

**Issue by hdrouard** [AdobeDocs/campaign-classic.en#10]
Issue in ./help/rn/using/latest-release.md

The title of the tab is "Release 19.1" whereas the latest build the release 19.2. The title should be updated to "Release 19.2"

![image](https://user-images.githubusercontent.com/60646646/73731511-e55c6600-4738-11ea-85f7-43f9f9f5d59e.png)

**Comment by Alicesnk** [comment]
The issue is now fixed.
