### ISSUE TITLE
User requirements and permissions should be added to doc

### ISSUE THREAD

**Issue by sharchen107** [AdobeDocs/campaign-classic.en#10]
My customer's comments:

The document did not disclose the user requirements & permissions needed to create the connector, this resulted in a support Ticket E-000646602 which took 22 days to resolve,

**Comment by Alicesnk** [comment]
@sharchen107 , please confirm which connector this issue is referring to. Thanks

**Comment by sharchen107** [comment]
Hi, this pertains to the new Analytics connector.  This is the documentation my customer was following that was incomplete:
https://experienceleague.adobe.com/docs/campaign-classic/using/getting-started/connectors/analytics-connector/adobe-analytics-provisioning.html?lang=en

**Comment by Alicesnk** [comment]
internal ref > DOCAC-9530

**Comment by Alicesnk** [comment]
The issue is now resolved. Thanks for your feedback.
