### ISSUE TITLE
AMP for Email support  in Outlook.com stopped 2 years ago, 9 September 2020

### ISSUE THREAD

**Issue by dburwitz** [AdobeDocs/campaign-classic.en#11]
Issue in ./help/delivery/using/defining-interactive-content.md
This page states that Outlook would support AMP Email. But Outlook stopped support AMP emails since 09 September 2020. See [Developer preview of AMP for email in Outlook.com - no longer supported](https://techcommunity.microsoft.com/t5/outlook-blog/developer-preview-of-amp-for-email-in-outlook-com-no-longer/ba-p/821020#individual-mailbox-registration)
The page references https://docs.microsoft.com/en-gb/outlook/amphtml/ and further URLs below that. 
They all redirect to [Developer preview of AMP for email in Outlook.com - no longer supported](https://techcommunity.microsoft.com/t5/outlook-blog/developer-preview-of-amp-for-email-in-outlook-com-no-longer/ba-p/821020#individual-mailbox-registration)

> Update (September 9th, 2020): Today we are announcing that, based on the results and feedback we received, the developer preview of AMP for Email will end on October 1st. 

 

> After that date, AMP for Email will be turned off in Outlook.com. Emails that used AMP will instead render using regular HTML; there is nothing extra email senders need to do for this fallback to work automatically. If email senders want to send dynamic emails to Outlook users, we encourage you to leverage [Actionable Messages](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.microsoft.com%2Fen-us%2Foutlook%2Factionable-messages%2F&data=04%7C01%7CAimee.Sudeck%40microsoft.com%7C3472370dbaad440b304d08d854fcd1a7%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637352792112079670%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=4dyr6igJBsrIGbn7c3ZYPEdBstCD0DAFbbk8m4Uo4T8%3D&reserved=0) instead.

**Comment by Alicesnk** [comment]
DOCAC-8113

**Comment by Alicesnk** [comment]
Thanks for the heads up @dburwitz, this is now fixed
