### ISSUE TITLE
Potentially incorrect setting indicated for turning on Email Link Signing

### ISSUE THREAD

**Issue by mihenry497** [AdobeDocs/campaign-classic.en#12]
Issue in ./help/installation/using/privacy.md

I was review this section of the Privacy documentation for the  **URL signature** and in the sub-section for turning on the signing it indicates to set the configuration parameter signEmailLinks to "false" to turn it on, when I believe it needs to be set to "true" to turn it on.

       To enable URL signature, follow these steps on all Campaign servers at the same time:

        In the server configuration file (serverConf.xml), change signEmailLinks to **false**.
        Restart the nlserver service.
        On the tracking server, restart the web server (apache2 on Debian, httpd on CentOS/RedHat, IIS on Windows).

Thanks,
Michael

**Comment by Alicesnk** [comment]
DOCAC-8112

**Comment by juliette-massardier** [comment]
Already fixed: https://experienceleague.adobe.com/docs/campaign-classic/using/installing-campaign-classic/security-privacy/privacy.html?lang=en#url-signature
