### ISSUE TITLE
No instructions on updating key pairs

### ISSUE THREAD

**Issue by alisonasanchez** [AdobeDocs/campaign-classic.en#13]
Issue in ./help/integrations/using/configuring-adobe-io.md
The doc says:
"The keys will then be automatically downloaded with a default expiry date of 365 days. Once expired, you will need to create a new key pair and update the integration in the configuration file. Using the Option 2, you can choose to manually create and upload your Public key with a longer expiry date."

Specific instructions on how to update the expired key pair would be helpful. It mentions a "configuration file" but there's no location for this file or example of how it is to be updated.

**Comment by Alicesnk** [comment]
[DOCAC-8111]

**Comment by Alicesnk** [comment]
Thanks for your feedback @alisonasanchez, this is now solved
