### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by sergioNYC** [AdobeDocs/campaign-classic.en#14]
Issue in ./help/configuration/using/data-model-best-practices.md

Under Name (or internal name), in the Best Practices column, 1st bullet, there is a typo:

It reads:  Rename the record name generated by Adobe Campaign if the object is meant to be deploy from an environment to another.

Should be:  Rename the record name generated by Adobe Campaign if the object is meant to be _**_**deployed**_**_ from an environment to another.

Also, in the same section, under bullet number four:

It reads:  Do not use special characters such as space “ “, semi-column “:” or hyphen “-“. All these characters would be replaced by an underscore “_” (allowed character). For example, “abc-def” and “abc:def” would be stored as “abc_def” and overwrite each other.

Should be:  Do not use special characters such as space “ “, semicolon “:” or hyphen “-“. All these characters would be replaced by an underscore “_” (allowed character). For example, “abc-def” and “abc:def” would be stored as “abc_def” and overwrite each other.

**Comment by Alicesnk** [comment]
Thanks for raising this. This is now resolved
