### ISSUE TITLE
Step description does not match screenshot or UI screen

### ISSUE THREAD

**Issue by abhardwaj-dev** [AdobeDocs/campaign-classic.en#15]
Issue in ./help/delivery/using/creating-seed-addresses.md

This point "In the Seed fields tab, enter the values that will be inserted in the delivery logs during the analysis phase (in the nms:broadLog table)" does not match the preceding screenshot nor does it match what is in the UI for v7 or v8. It needs to be removed from the documentation or corrected to show the tab name visible in the screenshot and the client console. 
![Seeds documentation issue](https://user-images.githubusercontent.com/98126932/214154296-6a1edc81-2b17-404d-8abf-f755b8aa5adf.png)

**Comment by Alicesnk** [comment]
DOCAC-8516

**Comment by Alicesnk** [comment]
Thanks for raising this issue. This is now resolved.
