### ISSUE TITLE
Page is obsolete for latest AEM versions, make it applicable for respective aem version

### ISSUE THREAD

**Issue by masumalli** [AdobeDocs/campaign-classic.en#15]
Issue in ./help/integrations/using/configuring-ims.md

The Latest version AEM has the IMS configuration package, you don't need to install. Please check with engineers and make it applicable for respective aem version

**Comment by manbeneat** [comment]
Hi,
Thanks for your comment!
I'm not sure I understand, do you mean that you don't need to install the **Integration with the Adobe Experience Cloud** package to use the IMS configuration since it is already available in the latest version of the **AEM** package?
Thanks!

Manon
