### ISSUE TITLE
There are 2 SDKs to add Campaign v8 or v7 to mobile app

### ISSUE THREAD

**Issue by dburwitz** [AdobeDocs/campaign-classic.en#16]
Issue in ./help/delivery/using/integrating-campaign-sdk-into-the-mobile-application.md
Next to Campaign SDK (previously known as Neolane SDK) there is Adobe Experience Platform Mobile SDK 
Key pointers 
- documentation home https://developer.adobe.com/client-sdks/documentation/
- release notes for Campaign Classic https://developer.adobe.com/client-sdks/documentation/adobe-campaign-classic/release-notes/
The new SDK has advantages (integration of other Adobe DX solutions, dynamic configuration, support for SWIFT) over the Neolane SDK

**Comment by Alicesnk** [comment]
The 2 SDKs are already mentioned in the documentation but we added a specific note to clarify. HTH
v7 > https://experienceleague.adobe.com/docs/campaign-classic/using/sending-messages/sending-push-notifications/integrating-campaign-sdk-into-the-mobile-application.html?lang=en 
v8 > https://experienceleague.adobe.com/docs/campaign/campaign-v8/campaigns/send/push.html?lang=en#push-sdk
