### ISSUE TITLE
Difficult to interpret.

### ISSUE THREAD

**Issue by ankurmehrotra** [AdobeDocs/campaign-classic.en#17]
Issue in ./help/workflow/using/defining-approvals.md

Is there a way to rephrase this, it is very hard to understand specially when you are not a native english speaker.

_An expiration can be used to trigger an action after a given lapse of time in the absence of a response or to pursue the workflow (and assign an approval to a different group, for example)._

**Comment by manbeneat** [comment]
Hi,
Thanks for your comment!
I updated the sentence as follows:

_You can use an expiration to trigger an action after a given time without response. It can also be used, for example, to pursue the workflow and assign an approval to a different group._

Hope this is clearer 

Manon
