### ISSUE TITLE
Misleading ACC Version Information

### ISSUE THREAD

**Issue by mihenry497** [AdobeDocs/campaign-classic.en#18]
Issue in ./help/message-center/using/event-description.md

This help document is linked from V8 Message Center help documentation, https://experienceleague.adobe.com/docs/campaign/campaign-v8/campaigns/send/transactional.html?lang=en, however it indicates at the top of this page that this is only Relevant for V7.

![image](https://user-images.githubusercontent.com/114672280/231823331-3405a9af-9eed-4df2-b96c-63fcadcba8a7.png)

Is this relevant for V8 as well?  Is the link incorrect or the notification on the page?

Thanks,
Michael

**Comment by Alicesnk** [comment]
Thanks for your feedback @mihenry497. This page is now available in V8 documentation here > https://experienceleague.adobe.com/docs/campaign/campaign-v8/campaigns/send/real-time/event-description.html?lang=en
