### ISSUE TITLE
nlserver config -postupgrade -allinstances

### ISSUE THREAD

**Issue by pnsoni3** [AdobeDocs/campaign-classic.en#19]
Below Step needs in Linux platform as well 

Synchronize resources {#synchronize-resources}
Use the following command line:

nlserver config -postupgrade -allinstances

This will enable you to carry out the following operations:

Synchronize resources,
update schemas,
update the database.
[!NOTE]

This operation should be performed only once, and only on an (nlserver web) application server.

**Comment by floflo492** [comment]
Thanks for your input. We are investigating the issue. We'll let you know when it is live.
Florent

**Comment by FlorentVAdobe** [comment]
I checked with engineering. No modification needed. Current documentation is accurate. As explained, the synchronization is performed automatically by the dpkg/rmp. 

« Resources are synchronized automatically, however you need to make sure no errors occurred. For more on this, refer to Resolving upgrade conflicts . »
