### ISSUE TITLE
Latest stable vs. other stables...

### ISSUE THREAD

**Issue by ghost** [AdobeDocs/campaign-classic.en#2]
Issue in ./help/rn/using/rn-overview.md

Different variants of "stable" might confuse the reader. We have

- getting the latest and greatest in your hands
- run the most recent stable version
- on a recent build 
- most recent builds
- the latest stable version
-  stable build on all servers
- the same build 
- each new release.
- most current versions of related
-  most up-to-date versions
-  the latest stable build 
- the current build
- new build

Maybe one could outline that "latest stable version" and "most recent stable version" means in relation to GA, LA, RC...

**Comment by Alicesnk** [comment]
Fixed
