### ISSUE TITLE
Change the SQL spell

### ISSUE THREAD

**Issue by psangra** [AdobeDocs/campaign-classic.en#20]
Need to correct the spell of SQL in the following sentence on the page
https://experienceleague.adobe.com/docs/campaign-classic/using/automating-with-workflows/use-cases/designing-queries/querying-recipient-table.html?lang=en

The Generated QSL queries tab shows the query result in SQL format.
Issue in ./help/workflow/using/querying-recipient-table.md

**Comment by Alicesnk** [comment]
Thanks for your feedback @psangra - we'll update shortly
Internal reference > /DOCAC-10300

**Comment by Alicesnk** [comment]
This issue has been resolved
