### ISSUE TITLE
Create a report based on workflow exclusion volume (audit)

### ISSUE THREAD

**Issue by eddiegolby** [AdobeDocs/campaign-classic.en#24]
Hello,

I would like to create an audit report (to send via email, automated if possible) to be able to monitor exclusion volume on automated workflows. In particular, I want to be able to output the volume of inclusion queries, exclusion queries, intersection results/complements etc... so there is a long-term log. Is this possible?

Thanks!

**Comment by Alicesnk** [comment]
please post questions to Campaign Community forum here > https://experienceleaguecommunities.adobe.com/t5/adobe-campaign-classic/ct-p/adobe-campaign-classic-community
