### ISSUE TITLE
Error staring campaign server "Adobe Campaign Classic v7 Server version- 7.0.9346"

### ISSUE THREAD

**Issue by vidhyabhushanbahl** [AdobeDocs/campaign-classic.en#3]
We have tried to install “Adobe Campaign Classic v7 Server version- 7.0.9346” on Windows 2016 server which as Oracle JDK 8. After the installation while starting the server using

_nlserver start web_ we are getting following error.  Can you help?

![image](https://user-images.githubusercontent.com/49717758/153398442-cf4705fb-62a8-4daf-bdfa-11aaa5541e41.png)

**Comment by Alicesnk** [comment]
Please open a support ticket
