### ISSUE TITLE
Links don't direct you to new page

### ISSUE THREAD

**Issue by KotakJacqueline** [AdobeDocs/campaign-classic.en#36]
Issue in ./help/delivery/using/a-b-testing-use-case.md

The links to other parts of the use case aren't working. 

For example: This link doesn't work. You aren't directed to the second step. Instead you stay on the overview page...
https://experienceleague.adobe.com/docs/campaign-classic/using/sending-messages/a-b-testing/use-case/a-b-testing-use-case.html?lang=en#step-2--configuring-population-samples

Please fix the links.

**Comment by lemaitreAdobe** [comment]
Hi @KotakJacqueline , thanks for your feedback. The links have been corrected.
