### ISSUE TITLE
Deprecated RDBMS versions, from which ACC version

### ISSUE THREAD

**Issue by chefness** [AdobeDocs/campaign-classic.en#37]
Issue in ./help/rn/using/deprecated-features.md

Hi there,
The page mentions which RDBMS Server versions are no longer supported (below), but it would be useful to state which Release they are no longer supported from (e.g. from 19.1 etc.)
This will be very useful for migrations and upgrade projects.

I see that 'Starting 19.1 release, ' is clearly mentioned for OS, Web servers etc.
Please mention it for RDBMS as well.

Thanks!

Text:
RDBMS SERVER

Adobe Campaign is not compatible with the following RDBMS Servers:

Oracle 10GR2
PostgreSQL 9.0 to 9.3
SQL Server 2005
MySQL 5.1
DB2 UDB 9.7

**Comment by Alicesnk** [comment]
Issue logged
