### ISSUE TITLE
404 - Deprecated and Removed Features article missing

### ISSUE THREAD

**Issue by manchika8** [AdobeDocs/campaign-classic.en#39]
The link to Deprecated and Removed Features article shows 404 page. Please update the link

**Comment by manchika8** [comment]
![Capture](https://user-images.githubusercontent.com/62883886/111739047-624c8f80-88a8-11eb-9840-250f174cd0c1.PNG)

**Comment by Alicesnk** [comment]
Please indicate where is the broken link so that we can fix. The page itself is there: https://experienceleague.adobe.com/docs/campaign-classic/using/release-notes/deprecated-features.html?lang=en#release-notes

**Comment by manchika8** [comment]
The link currently present in the page does not refer to what was shared. Please see the attachment. 
![Capture](https://user-images.githubusercontent.com/62883886/111799688-41f4f300-88f1-11eb-8e68-f364ffa12c9e.PNG)
