### ISSUE TITLE
Incorrect or outdated screenshot

### ISSUE THREAD

**Issue by abhardwaj-dev** [AdobeDocs/campaign-classic.en#6]
Issue in ./help/installation/using/installing-the-server.md

The screenshot that shows up after the command "nlserver web" is incorrect and does not apply as it shows the result of the command "nlserver start web" I'm attaching the screenshot that should be deleted as it adds no value and could cause confusion for the end user. 
![Screenshot 2022-03-22 085131](https://user-images.githubusercontent.com/98126932/159497181-49c869f9-6ae4-42e2-81c6-4c60439599bf.png)

**Comment by Alicesnk** [comment]
DOCAC-8115

**Comment by Alicesnk** [comment]
DOCAC-8115

**Comment by FlorentVAdobe** [comment]
The screenshot has been removed.
