### ISSUE TITLE
Outdated File Collector screenshot and options

### ISSUE THREAD

**Issue by abhardwaj-dev** [AdobeDocs/campaign-classic.en#7]
Issue in ./help/workflow/using/file-collector.md

The setting "Process file nonexistence" is now called "Process missing file"
The setting "Processing errors" is now called "Process errors"

The screenshot needs to be updated.

![image](https://user-images.githubusercontent.com/98126932/163280922-0198b2c7-5c0b-483a-abe8-a9b0b4e1b503.png)

**Comment by Alicesnk** [comment]
DOCAC-8114
